// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cymajdjmoysmxvvbitqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bWFqZGptb3lzbXh2dmJpdHFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1ODc2NjAsImV4cCI6MjA1NjE2MzY2MH0.KitJmIPEUG6CZZ4U65yMQ0tejx4RrFmcq48p65Mf-g0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);